eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: searchService
          uri: http://localhost:8070
          predicates:
            - Path= /**
        - id: notificationService
          uri: http://localhost:8090
          predicates:
            - Path= /**
  application:
    name: apiGateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/my_realm
  config:
    import: optional:configserver:http://localhost:8888
